### ISSUE TITLE
Use .lesshintrc

### ISSUE THREAD

**Issue by fynnfeldpausch** [kokarn/grunt-lesshint#1]
Is it possible to place the less hint config in a separate config file? How it it specified in the grunt file?

**Comment by kokarn** [comment]
I haven't actually tested this but it should be possible. I'll look into it ASAP

**Comment by kokarn** [comment]
Hello again!

```grunt-lesshint``` has been updated to ```0.4.0``` with support for custom ```.lesshintrc``` files.

If you want to have a look at the implementation, the relevant commit is this https://github.com/kokarn/grunt-lesshint/commit/54ee39d7a5685060ba2182c597e330db072e5b37.

Thanks for reporting this! <3
